server:
  port: 10000
  servlet:
    context-path: /project-management
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=pm;SelectMethod=cursor
    username: 'sa'
    password: '123456'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl